homeassistant: !include configurations/main.yaml

automation: !include automations.yaml
binary_sensor: !include_dir_list binary_sensors/
camera: !include_dir_list cameras/
cloud: !include_dir_named cloud/
device_tracker: !include_dir_list device_trackers/
ecobee: !include integrations/ecobee.yaml
group: !include configurations/groups.yaml
http: !include configurations/http.yaml
hydrawise: !include integrations/hydrawise.yaml
ifttt: !include integrations/ifttt.yaml
media_player: !include_dir_list media_players/
mqtt: !include configurations/mqtt.yaml
nest: !include integrations/nest.yaml
notify: !include_dir_list notifiers/
nuheat: !include integrations/nuheat.yaml
panel_iframe: !include_dir_named menu_items/
remote: !include_dir_list remotes/
ring: !include integrations/ring.yaml
script: !include configurations/scripts.yaml
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
tts: !include_dir_list speech_engines/
tuya: !include integrations/tuya.yaml
zha: !include protocols/zigbee.yaml
zwave: !include protocols/zwave.yaml

config:
conversation:
discovery:
frontend:
history:
logbook:
map:
sun:
updater:

logger:
  default: info
